Remove invalid name from python code
LibreLingo/LibreLingo pull request #2486
Opened 2022-10-12 16:58 UTC by LokeshShelva

Enables the pylint config - invalid_name
fixes #1928

2022-10-12 17:19 UTC, LokeshShelva commented
So, the CI/CD is passing but when I run pylint in my local machine, I can find the errors. I will change the errors for now. Let me know what to do.
Also can we add "f" as a good name in pylint, as mostly it will be used to open files?

2022-10-19 18:46 UTC, kantord commented
> Also can we add "f" as a good name in pylint, as mostly it will be used to open files?

I wonder if that's considered good practice, do you have some source for that (perhaps an article saying best practices for naming file pointers for python or sth like that)

2022-10-19 18:46 UTC, kantord commented
Looks like the checks are not running at all, I wonder why. Let me check out the GitHub Actions configuration

2022-10-19 18:50 UTC, kantord commented
Can you please try to rebase this PR to `main` @LokeshShelva ? It seems like I would need to do this to run the checks: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks however, that button is not even there, so I think that it migth be that you created this from an older version of the main branch that still did not have the github actions configuration. That's the only reason I can think of right now :thinking:

2022-10-22 05:36 UTC, LokeshShelva commented
@kantord, I think I rebased this PR.

2022-10-23 14:52 UTC, kantord commented
> @kantord, I think I rebased this PR.



> @kantord, I think I rebased this PR.

Hi @LokeshShelva , I figured out what the problem was. Your PR was not triggering the pipelines because I accidentally set up the pipelines to only be triggered on `push`, not on `pull_request`. That's a problem because `push` is not triggered on forks, on the other hand, pull request should be.

I [fixed it,](https://github.com/LibreLingo/LibreLingo/commit/e1923fc7736f91b4a7e6e2b5f64763f14fea8eb8) but sorry about it, but you should rebase your PR again to the most up to date version of `main` in order to see the failures on this pull request.

2022-10-24 05:24 UTC, LokeshShelva commented
@kantord. Thank you. I will work on it .

2022-10-27 15:39 UTC, LokeshShelva commented
@kantord, So I have added the variable name `fs` as a good name in pylint as the pytest uses that name as a fixture if I am not wrong.  We could also disabling invalid name check only in the needed blocks and remove `fs` from good names list. I think this will be better.

Also I disables invalid-name check  on [`apps/librelingo_yaml_loader/librelingo_yaml_loader/_spelling.py`](https://github.com/LibreLingo/LibreLingo/blob/03ce7c4ba58b8c32f35dd0feb4f5c58fbc66cdde/apps/librelingo_yaml_loader/librelingo_yaml_loader/_spelling.py#L3). It uses the `hunspell` modules and the name does not conform with pylint.

Do you have any suggestion for these two?

2022-10-29 10:14 UTC, kantord requested changes
Hi, there are some small details but otherwise looks good!

if you want, you can watch my review: https://www.youtube.com/watch?v=1-MAeFngEyM

2022-10-29 16:40 UTC, LokeshShelva commented on apps/librelingo_json_export/tests/test_integration.py
> +        return json.load(file_path)
I think `json_file` might be a better name here

2022-10-29 18:25 UTC, LokeshShelva commented on pylintrc
> +           fs
fs is not a good name. I removed it. Now pylint is ignored at the required blocks.

2022-11-05 16:42 UTC, kantord commented
Hi @LokeshShelva , I could not merge this because there are some conflicts. Can you please resolve them?

2022-11-05 16:42 UTC, kantord commented on pylintrc
> +           fs
perfect, thanks!

2023-01-14 11:49 UTC, kantord commented
closing because it's stale and there was no response. feel free to reopen if you can do the conflic resolution

2023-01-14 11:49 UTC, closed without merging